server:
  port: 8082

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: root
  zipkin:
    base-url: http://localhost:9411/
#  jpa:
#    hibernate:
#      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

api:
  service:
    reservation:
      name: reservation-service
      path: /reservations
